# Esto ya lo traía al descargar de Spring
spring.application.name=finanz-api
# Añadimos:
sring.datasource.url=jdbc:h2:file:./data/finanz-api
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.usernmae=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## H2 es una base de datos embebidaq ue no necesita instalación. Con jdbc:h2:file:
## los datos se guardan en disco igualq ue hacíamos con el .csv, pero ahora es una
## BD real. La consola H2 en /h2-console te permite inspeccionar los datos desde el
## navegador mientras desarrolla.
## Ahora pasaremos a Entidades JPA, módulo 1, 